In [3]:
import numpy as np
b = np.array ([(1.5 ,2 ,3) , (4 ,5 ,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [4]:
b.shape

(2, 3)

In [5]:
b - b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
b*(b+5)

array([[  9.75,  14.  ,  24.  ],
       [ 36.  ,  50.  ,  66.  ]])

In [7]:
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [9]:
>>> b[:2 ,:2]

array([[ 1.5,  2. ],
       [ 4. ,  5. ]])

In [11]:
np.linalg.inv(b[:2, :2])

array([[-10.,   4.],
       [  8.,  -3.]])